// app/components/vapor/ProductCard.vue
<script setup lang="ts">
import { computed } from "vue";
import type { Product } from "~/types";
import { useVape } from "~/composables/useVape";
import { money, haptic, CATS_META } from "~/utils/vape";
import { HeartIcon, PlusIcon, StarIcon } from "~/components/vapor/VIcons";

const props = withDefaults(
  defineProps<{
    p: Product;
    index?: number;
  }>(),
  {
    index: 0,
  }
);

const { add, inWish, toggleWish } = useVape();

const out = computed(() => props.p.stock <= 0);
const price = computed(() => props.p.discountPrice ?? props.p.price);
const pct = computed(() =>
  props.p.discountPrice ? Math.round(((props.p.price - props.p.discountPrice) / props.p.price) * 100) : 0
);
const saved = computed(() => inWish(props.p.id));
const flavorHint = computed(() => props.p.tagline);

const onAdd = () => {
  if (out.value) return;
  haptic(10);
  add({
    id: props.p.id,
    slug: props.p.slug,
    name: props.p.name,
    img: props.p.images[0] ?? "",
    price: price.value,
    oldPrice: props.p.discountPrice != null ? props.p.price : null,
    stock: props.p.stock,
  });
};
</script>

<template>
  <div class="group relative">
    <div class="card-g relative overflow-hidden rounded-[20px] transition-all duration-500 hover:border-vio/40 hover:glow-v active:scale-[0.985]">
      <NuxtLink :to="`/product/${p.slug}`" class="relative block overflow-hidden">
        <div class="aspect-[4/5] overflow-hidden bg-panel">
          <img
            :src="p.images[0]"
            :alt="p.name"
            :loading="index < 4 ? 'eager' : 'lazy'"
            decoding="async"
            class="h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.06]"
          />
        </div>
        <!-- نور نئونی روی لبه هنگام لمس/هاور -->
        <div class="pointer-events-none absolute inset-0 rounded-[20px] bg-gradient-to-t from-ink/60 via-transparent to-transparent opacity-80" />

        <!-- بج‌ها در بالا سمت راست -->
        <div class="absolute top-3 right-3 z-10 flex flex-wrap items-center gap-1.5 pointer-events-none">
          <span
            v-if="pct > 0"
            class="rounded-xl bg-gradient-to-l from-neon to-ice px-2.5 py-1 text-[11px] font-extrabold text-ink tnum shadow-sm"
            dir="ltr"
          >
            ٪{{ pct }}
          </span>
          <span
            v-if="p.newArrival"
            class="rounded-xl bg-vio/85 px-2.5 py-1 text-[10.5px] font-extrabold text-white backdrop-blur shadow-sm"
          >
            جدید
          </span>
        </div>
        <span
          v-if="out"
          class="absolute inset-0 grid place-items-center bg-ink/60 backdrop-blur-[2px] text-[13px] font-extrabold text-blush"
        >
          ناموجود
        </span>
      </NuxtLink>

      <!-- دکمه علاقه‌مندی - همیشه در گوشه بالا چپ -->
      <button
        class="pressable absolute top-3 left-3 z-10 grid h-10 w-10 place-items-center rounded-full backdrop-blur-md border border-white/10 transition-colors cursor-pointer"
        :class="[
          saved
            ? 'bg-blush text-ink shadow-[0_0_14px_rgba(240,171,252,0.5)]'
            : 'bg-ink/60 text-snow hover:bg-ink/80 hover:text-blush',
        ]"
        :aria-pressed="saved"
        :aria-label="saved ? 'حذف از علاقه‌مندی‌ها' : 'افزودن به علاقه‌مندی‌ها'"
        @click="toggleWish(p.id, p.name)"
      >
        <HeartIcon :size="18" :filled="saved" />
      </button>

      <div class="p-3.5">
        <div class="flex items-center justify-between gap-2">
          <p dir="ltr" class="truncate text-[12.5px] font-extrabold tracking-wide text-snow">{{ p.name }}</p>
          <span class="flex shrink-0 items-center gap-1 text-[11px] font-bold text-gold tnum" dir="ltr">
            <StarIcon :size="12" :filled="true" class="text-gold" />
            {{ p.rating.toFixed(1) }}
          </span>
        </div>
        <p v-if="flavorHint" class="mt-1 truncate text-[11px] text-mist">{{ flavorHint }}</p>
        <p class="mt-0.5 text-[10px] font-bold text-dim" dir="ltr">
          {{ p.brand }} · {{ CATS_META[p.categorySlug]?.label ?? "" }}
        </p>

        <div class="mt-3 flex items-center justify-between gap-2">
          <div>
            <p class="text-[13.5px] font-extrabold text-snow tnum">{{ money(price) }}</p>
            <p v-if="p.discountPrice != null" class="text-[10.5px] text-dim line-through tnum">{{ money(p.price) }}</p>
          </div>
          <button
            :disabled="out"
            class="pressable grid h-12 w-12 shrink-0 place-items-center rounded-2xl transition-all duration-300 cursor-pointer"
            :class="[
              out
                ? 'bg-white/6 text-dim'
                : 'bg-gradient-to-br from-vio to-ice text-ink shadow-[0_6px_22px_-6px_rgba(167,139,250,0.65)]',
            ]"
            :aria-label="`افزودن ${p.name} به سبد`"
            @click="onAdd"
          >
            <PlusIcon :size="22" :sw="2.4" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/ProductCard.tsx
"use client";

import Link from "next/link";
import type { Product } from "@/lib/types";
import { cn, discountPct, fmt } from "@/lib/utils";
import { useStore } from "@/store/store";
import { Stars, Price, Badge } from "@/components/ui";
import { IcHeart, IcEye, IcCart } from "@/components/icons";

export function ProductCard({ product: p, index = 0 }: { product: Product; index?: number }) {
  const { addToCart, inWishlist, toggleWishlist, setQuickView, hydrated } = useStore();
  const out = p.stock <= 0;
  const saved = inWishlist(p.id);
  const pct = discountPct(p.price, p.discountPrice);

  return (
    <div className="group relative" style={{ animationDelay: `${index * 40}ms` }}>
      <div className="card-surface relative overflow-hidden rounded-xl transition-all duration-500 group-hover:-translate-y-1 group-hover:border-line2 group-hover:shadow-[0_24px_48px_-20px_rgba(0,0,0,0.7)]">
        {/* images */}
        <div className="relative aspect-[4/5] overflow-hidden bg-card">
          {p.images.slice(0, 2).map((img, i) => (
            <Link href={`/product/${p.slug}`} key={i} aria-label={i === 0 ? p.name : undefined} className="absolute inset-0">
              <img
                src={img}
                alt={i === 0 ? p.name : ""}
                loading={index < 4 ? "eager" : "lazy"}
                decoding="async"
                className={cn(
                  "h-full w-full object-cover transition-all duration-[900ms] ease-[cubic-bezier(0.22,1,0.36,1)] group-hover:scale-[1.06]",
                  i === 1 ? "opacity-0 group-hover:opacity-100" : "opacity-100"
                )}
              />
            </Link>
          ))}
          {/* soft light sweep on hover */}
          <div className="pointer-events-none absolute inset-0 bg-gradient-to-tr from-transparent via-white/[0.05] to-transparent opacity-0 transition-opacity duration-700 group-hover:opacity-100" />

          {/* badges */}
          <div className="absolute top-3 left-3 flex flex-col items-start gap-1.5">
            {p.newArrival && <Badge tone="gold">New</Badge>}
            {pct > 0 && <Badge tone="neutral" className="bg-black/50 backdrop-blur">-{pct}%</Badge>}
            {p.bestSeller && !p.newArrival && <Badge tone="neutral" className="bg-black/50 backdrop-blur">Best seller</Badge>}
          </div>

          {/* wishlist */}
          <button
            onClick={() => toggleWishlist({ id: p.id, name: p.name })}
            aria-label={saved ? `Remove ${p.name} from wishlist` : `Save ${p.name} to wishlist`}
            aria-pressed={saved}
            className={cn(
              "absolute top-3 right-3 grid h-10 w-10 place-items-center rounded-full backdrop-blur-md transition-all duration-300 md:translate-x-2 md:opacity-0 md:group-hover:translate-x-0 md:group-hover:opacity-100",
              saved ? "bg-gold text-[#0c0c0e]" : "bg-black/45 text-cream hover:bg-black/70"
            )}
          >
            <IcHeart size={17} filled={saved} />
          </button>

          {/* hover actions */}
          <div className="absolute inset-x-3 bottom-3 flex translate-y-14 gap-2 opacity-0 transition-all duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] group-hover:translate-y-0 group-hover:opacity-100">
            <button
              onClick={() => addToCart({ id: p.id, slug: p.slug, name: p.name, price: p.discountPrice ?? p.price, compareAt: p.discountPrice ?? null, image: p.images[0] ?? "", stock: p.stock })}
              disabled={out}
              className="flex h-11 flex-1 items-center justify-center gap-2 rounded-[10px] bg-cream text-[12px] font-semibold tracking-wide text-[#0c0c0e] transition-all duration-300 hover:bg-white disabled:cursor-not-allowed disabled:opacity-60"
            >
              <IcCart size={15} /> {out ? "Out of stock" : "Add to cart"}
            </button>
            <button
              onClick={() => setQuickView(p)}
              aria-label={`Quick view ${p.name}`}
              className="grid h-11 w-11 place-items-center rounded-[10px] bg-black/55 text-cream backdrop-blur-md transition-colors duration-300 hover:bg-black/80"
            >
              <IcEye size={17} />
            </button>
          </div>

          {out && (
            <div className="absolute inset-0 grid place-items-center bg-black/45 backdrop-blur-[2px]">
              <span className="rounded-full border border-line2 bg-black/60 px-4 py-1.5 text-[11px] font-semibold tracking-[0.18em] text-cream/90 uppercase">
                Out of stock
              </span>
            </div>
          )}
        </div>

        {/* info */}
        <div className="p-4 md:p-5">
          <p className="mb-1.5 text-[10.5px] font-semibold tracking-[0.18em] text-faint uppercase">
            {p.brand} · {p.category}
          </p>
          <Link href={`/product/${p.slug}`} className="block">
            <h3 className="truncate text-[15px] font-medium text-cream transition-colors duration-300 group-hover:text-goldsoft">
              {p.name}
            </h3>
          </Link>
          <div className="mt-2 flex items-center gap-2">
            <Stars value={p.rating} size={12} />
            <span className="text-[11px] text-faint tnum">({p.reviewCount})</span>
          </div>
          <div className="mt-2.5">
            <Price price={p.discountPrice ?? p.price} compareAt={p.discountPrice ? p.price : null} size="sm" />
          </div>
        </div>
      </div>
    </div>
  );
}
